import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { basename, dirname, join, relative, resolve } from "node:path"
import { renderHtml } from "./render-lib"

const input = process.argv[2]
if (input === undefined) {
  console.error("usage: bun render-tree.ts <docs-dir> [outdir]")
  console.error("Renders every .md in the tree to .html (README.md → index.html),")
  console.error("copies other files as-is, and produces a publishable bundle.")
  process.exit(1)
}
const inputDir = resolve(input)
if (!existsSync(inputDir) || !statSync(inputDir).isDirectory()) {
  console.error(`not a directory: ${inputDir}`)
  process.exit(1)
}
const outDir =
  process.argv[3] !== undefined
    ? resolve(process.argv[3])
    : join(tmpdir(), "dossier-site", basename(inputDir))
const marker = join(outDir, ".dossier-site")

if (existsSync(outDir)) {
  if (!existsSync(marker)) {
    console.error(`refusing to overwrite ${outDir} — it exists and is not a render-tree output`)
    process.exit(1)
  }
  rmSync(outDir, { recursive: true, force: true })
}
mkdirSync(outDir, { recursive: true })
writeFileSync(marker, "generated by tap-skills render-doc/render-tree.ts\n")

const walk = (dir: string): string[] =>
  readdirSync(dir).flatMap((f) => {
    if (f.startsWith(".") || f === "CLAUDE.md") return []
    const p = join(dir, f)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })

const files = walk(inputDir)
const rootReadmePath = files.find((f) => relative(inputDir, f) === "README.md")
const rootReadme = rootReadmePath !== undefined ? readFileSync(rootReadmePath, "utf8") : null
const siteTitle =
  rootReadme?.match(/^#\s+(.+)$/m)?.[1] ?? basename(inputDir)

// wiki-link map: file basename (sans .md) → bundle-root-relative .html path.
// READMEs are excluded — "README" is not a meaningful wiki name and collides across dirs.
const wikiMap: Record<string, string> = {}
for (const file of files) {
  const rel = relative(inputDir, file)
  if (!file.endsWith(".md") || rel.endsWith("README.md")) continue
  wikiMap[basename(file, ".md")] = rel.replace(/\.md$/, ".html")
}

let pages = 0
let assets = 0
const toc: { outRel: string; title: string }[] = []
for (const file of files) {
  const rel = relative(inputDir, file)
  if (rel === "README.md") continue
  if (file.endsWith(".md")) {
    const outRel = rel.endsWith("README.md")
      ? rel.replace(/README\.md$/, "index.html")
      : rel.replace(/\.md$/, ".html")
    const depth = outRel.split("/").length - 1
    const rendered = renderHtml(readFileSync(file, "utf8"), basename(file, ".md"), {
      prefix: "../".repeat(depth),
      siteTitle,
      map: wikiMap,
    })
    mkdirSync(dirname(join(outDir, outRel)), { recursive: true })
    writeFileSync(join(outDir, outRel), rendered.html)
    toc.push({ outRel, title: rendered.title })
    pages++
  } else {
    mkdirSync(dirname(join(outDir, rel)), { recursive: true })
    copyFileSync(file, join(outDir, rel))
    assets++
  }
}

// root index: README (or a synthesized heading) + a generated Contents section, so
// every page is reachable — source trees are often navigated by file browser and
// carry no internal links
const groups = new Map<string, { outRel: string; title: string }[]>()
for (const entry of toc.sort((a, b) => a.outRel.localeCompare(b.outRel))) {
  const dir = dirname(entry.outRel)
  const list = groups.get(dir) ?? []
  list.push(entry)
  groups.set(dir, list)
}
let contents = "\n\n## Contents\n"
for (const [dir, entries] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  if (dir !== ".") contents += `\n### ${dir}/\n`
  else contents += "\n"
  for (const e of entries) contents += `- [${e.title}](${e.outRel})\n`
}
const indexSource = (rootReadme ?? `# ${basename(inputDir)}`) + contents
writeFileSync(
  join(outDir, "index.html"),
  renderHtml(indexSource, basename(inputDir), { prefix: "", siteTitle, map: wikiMap }).html,
)
pages++

console.log(`${outDir}`)
console.log(`${pages} pages, ${assets} assets`)
console.log(`publish: bun <publish-skill>/scripts/dossier.ts publish ${outDir} --slug=${basename(inputDir).toLowerCase()}`)
